"""Layer 1 of §9.3: measure how the pinned Open WebUI renders each delimiter style.

Renders every fixture case raw and normalized in each inline style, records
whether it rendered, writes docs/LATEX.md + docs/latex-render.png, and requires
every case to pass for the chosen style.
"""

from __future__ import annotations

import re
from datetime import datetime

from conftest import DOCS, FIXTURES, UI, env, load_normalizer

STYLES = ("dollar", "paren", "double")

# Evaluated in the page for one message: counts and text left outside math and code.
PROBE = r"""(el) => {
  const body = el.querySelector('#response-content-container') || el;
  const clone = body.cloneNode(true);
  clone.querySelectorAll('.katex, .katex-display, pre, code, .cm-editor, button, svg').forEach(n => n.remove());
  const code = Array.from(body.querySelectorAll('pre, code, .cm-content')).map(n => n.textContent).join('\n');
  return {
    katex: body.querySelectorAll('.katex').length,
    errors: body.querySelectorAll('.katex-error').length,
    display: body.querySelectorAll('.katex-display').length,
    text: clone.textContent,
    code: code,
  };
}"""

LEFTOVER = re.compile(r"\$\$|\\\[|\\\]|\\\(|\\\)|\\begin|\\end|\\frac|\\sum|\\boxed|(?<![\\\w])\$(?!\d)")


def parse_cases() -> list[dict]:
    text = (FIXTURES / "latex_matrix.md").read_text()
    cases = []
    for m in re.finditer(r"<!-- case: ([\w-]+) \| expect: (\w+) -->\n(.*?)(?=\n<!-- case:|\Z)", text, re.S):
        cases.append({"id": m.group(1), "expect": m.group(2), "src": m.group(3).strip("\n")})
    return cases


def judge(expect: str, probe: dict) -> tuple[bool, str]:
    if expect == "math":
        if probe["errors"]:
            return False, f"{probe['errors']} KaTeX error(s)"
        if probe["katex"] == 0:
            return False, "no math rendered"
        left = LEFTOVER.findall(probe["text"])
        if left:
            return False, "raw delimiters: " + " ".join(sorted(set(left)))
        return True, f"{probe['katex']} formula(s)"
    if expect == "literal":
        if probe["katex"]:
            return False, "prices rendered as math"
        if "$5" not in probe["text"] or "$10" not in probe["text"]:
            return False, "prices not shown literally"
        return True, "prices literal"
    if expect == "code":
        if probe["katex"]:
            return False, "math rendered inside code"
        return ("$x$" in probe["code"], "code literal" if "$x$" in probe["code"] else "code content changed")
    return False, f"unknown expectation {expect}"


def render_variant(
    ui, api, name: str, cases: list[dict], contents: list[str], shot: str | None = None
) -> list[tuple[bool, str]]:
    cid, asst_ids = api.create_chat(
        f"latex matrix — {name}", [(f"case {c['id']}", t) for c, t in zip(cases, contents, strict=True)]
    )
    ui.goto(f"{UI}/c/{cid}")
    ui.wait_for_selector(f"#message-{asst_ids[-1]}", timeout=60_000)
    # Open WebUI renders the newest messages first and loads older ones on scroll-up.
    for _ in range(40):
        if ui.locator(f"#message-{asst_ids[0]}").count():
            break
        ui.evaluate("() => { const c = document.getElementById('messages-container'); if (c) c.scrollTop = 0; }")
        ui.wait_for_timeout(400)
    results = []
    for aid, case in zip(asst_ids, cases, strict=True):
        el = ui.locator(f"#message-{aid}")
        el.scroll_into_view_if_needed()
        ui.wait_for_timeout(150)
        results.append(judge(case["expect"], el.evaluate(PROBE)))
    if shot:
        # The chat scrolls inside #messages-container: grow the viewport to capture every case.
        h = ui.evaluate("() => document.getElementById('messages-container')?.scrollHeight || 900")
        ui.set_viewport_size({"width": 1280, "height": min(int(h) + 250, 16000)})
        ui.wait_for_timeout(1200)
        ui.screenshot(path=shot, full_page=True)
        ui.set_viewport_size({"width": 1280, "height": 900})
    return results


def test_latex_render_matrix(ui, api):
    norm = load_normalizer()
    cases = parse_cases()
    assert len(cases) >= 20, "fixture parse failed"
    chosen = env("LEO_MATH_INLINE", "dollar")
    variants = {"raw": [c["src"] for c in cases]}
    for s in STYLES:
        variants[s] = [norm.normalize_math(c["src"], s) for c in cases]

    results = {}
    for name, contents in variants.items():
        shot = str(DOCS / "latex-render.png") if name == chosen else None
        results[name] = render_variant(ui, api, name, cases, contents, shot)

    passes = {name: sum(ok for ok, _ in r) for name, r in results.items()}
    recommended = max(STYLES, key=lambda s: (passes[s], -STYLES.index(s)))

    lines = [
        "# LaTeX rendering matrix",
        "",
        f"Generated by `make test-ui` on {datetime.now().astimezone():%Y-%m-%d %H:%M %Z} against `{UI}` "
        f"(Open WebUI `{env('OPENWEBUI_VERSION')}`), headless Chromium.",
        "",
        "Each fixture case (`tests/ui/fixtures/latex_matrix.md`) is rendered as an assistant message **raw** "
        "(as a model might write it) and **normalized** by `leo_latex_normalizer` in each inline style. "
        "A math case passes when KaTeX rendered it, with no `.katex-error` and no raw delimiters left in the text.",
        "",
        "| Case | Expect | " + " | ".join(variants) + " |",
        "|---|---|" + "---|" * len(variants),
    ]
    for i, c in enumerate(cases):
        cells = [("✅ " if results[v][i][0] else "❌ ") + results[v][i][1] for v in variants]
        lines.append(f"| `{c['id']}` | {c['expect']} | " + " | ".join(cells) + " |")
    lines += [
        "| **passed** | | " + " | ".join(f"**{passes[v]}/{len(cases)}**" for v in variants) + " |",
        "",
        f"Recommended inline style: `{recommended}`",
        "",
        f"Chosen inline style: `{chosen}` (from `LEO_MATH_INLINE`; bootstrap fills the system prompt and the "
        "normalizer valve with this style)",
        "",
        "Display math is always canonical: `$$` on its own line, the formula, `$$` on its own line, blank lines around.",
        "",
        "Known limits: formulas glued together in the raw text (`$a$$b$`) are ambiguous in any renderer; "
        "the normalizer separates them with a space. `double` inline style cannot be made idempotent for "
        "adjacent formulas and is not recommended.",
        "",
        "![rendered fixture](latex-render.png)",
        "",
    ]
    (DOCS / "LATEX.md").write_text("\n".join(lines))

    if recommended != chosen:
        print(f"\nNOTE: the matrix recommends LEO_MATH_INLINE={recommended} (currently {chosen}). Ask before changing.")
    failed = [f"{c['id']}: {results[chosen][i][1]}" for i, c in enumerate(cases) if not results[chosen][i][0]]
    assert not failed, f"chosen style '{chosen}' has failing cases: {failed}"
